name: sorted
description: >
  Sort lists of complex objects with ease.
  Simple but powerful extension method.
version: 2.1.0
homepage: https://github.com/Albert221/sorted

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0

dev_dependencies:
  build_runner: ^2.1.1
  lint: ^1.5.3
  mockito: ^5.0.15
  test: ^1.17.11
