name: sorted
description: Sort lists of complex objects with ease.
version: 1.0.0
homepage: https://github.com/Albert221/sorted

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  lint: ^1.3.0
  mockito: ^4.1.3
  test: ^1.15.4
