name: sorted
description: Sort Lists of objects with ease.
version: 1.0.0
homepage: https://github.com/Albert221/sorted

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.15.4
  lint: ^1.3.0
