name: sorted
description: >
  Sort lists of complex objects with ease.
  Simple but powerful extension method.
version: 2.0.0
homepage: https://github.com/Albert221/sorted

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.1
  lint: ^1.6.0
  mockito: ^5.0.15
  test: ^1.17.11
