name: Publish

on:
  push:
    tags: ['v*']

jobs:
  publish:
    name: Publish to pub.dev

    runs-on: ubuntu-latest

    container:
      image: google/dart:2.10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download pub.dev credentials
        env:
          CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
        run: |
          mkdir -p ~/.pub-cache
          echo $CREDENTIALS > ~/.pub-cache/credentials.json
      
      - name: Ignore not needed files
        run: echo .github >> .gitignore

      - name: Publish
        run: pub publish -f
